#!/bin/bash
cd mnt/jffs2/log/eng-repo/
fname=`grep -l -e BMC_OOM_RESET -e BMC_WATCHDOG messages messages.??.??`
for i in `echo $fname`
do
    if [ $i == "messages" ]
    then
       prevext=0
    else
        ext=`echo "$i" | cut -d'.' -f2`
        prevext=$(($ext+1))
    fi
    grep -e Oops -e 'BUG:' -e 'WARNING: CPU' -e 'resetted BMC due to OOM' -e 'oom-killer' $i >/dev/null 2>&1
    ret1=$?
    grep  -e Oops -e 'BUG:' -e 'WARNING: CPU' -e 'resetted BMC due to OOM' -e 'oom-killer' messages.$prevext >/dev/null
2>&1
    ret2=$?
    if [ $ret1 -ne 0 -a $ret2 -ne 0 ]
    then
        echo "matching pattern in $i for abrupt CIMC reset CSCvs15733"
    fi
done
